#!/bin/bash

FROM  espressif/idf:release-v4.4

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

ENV IDF_PYTHON_ENV_PATH=/usr/bin/

RUN set -x \
    && groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && adduser $USERNAME dialout

USER $USERNAME
